import { LoadingTask } from '../../components/Loading';
import React, { useRef, useState } from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ApiError, type ApiClient } from '../../api/client';
import { tagSchema, type Tag } from '../../shared/contracts';
import Action from '../../components/Action';
import SelectField from '../../components/SelectField';
import { colors as c, type as t } from '../../design/tokens';
export default function TagManager({ api, tags, onTags, onClose }: { api: ApiClient; tags: Tag[]; onTags: (tags: Tag[]) => void; onClose: () => void }) {
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState(false);
  const [original, setOriginal] = useState<Tag | null>(null);
  const [id, setId] = useState(''); const [label, setLabel] = useState(''); const [category, setCategory] = useState('vibe'); const [aliases, setAliases] = useState('');
  const [confirmDelete, setConfirmDelete] = useState(false); const [conflict, setConflict] = useState(false);
  const [busy, setBusy] = useState(false); const pending = useRef(false); const [error, setError] = useState('');
  const begin = (tag: Tag | null) => { setOriginal(tag); setId(tag?.id ?? ''); setLabel(tag?.label ?? ''); setCategory(tag?.category ?? 'vibe'); setAliases(tag?.aliases.join(', ') ?? ''); setConfirmDelete(false); setConflict(false); setError(''); setEditing(true); };
  const run = async (fn: () => Promise<void>) => { if (pending.current) return; pending.current = true; setBusy(true); setError(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update tags.'); if (e instanceof ApiError && e.status === 409) setConflict(true); } finally { pending.current = false; setBusy(false); } };
  const save = () => run(async () => {
    const checked = tagSchema.safeParse({ id, label, category, aliases: aliases.split(',').map(value => value.trim()).filter(Boolean) });
    if (!checked.success) throw new Error('Enter a label, a lowercase tag ID, and up to 40 aliases.');
    const result = await api.request<{ tags: Tag[] }>('/admin/tags/' + encodeURIComponent(id), 'PUT', { ...checked.data, expected: original });
    onTags(result.tags); setEditing(false);
  });
  return <View style={s.root}><View style={s.row}><Text style={[s.title, { flex: 1 }]}>{editing ? confirmDelete ? 'Delete shared tag?' : original ? 'Edit tag' : 'New tag' : 'Shared tags'}</Text><Action label={editing ? 'Back' : 'Done'} disabled={busy} onPress={() => editing ? setEditing(false) : onClose()} /></View>{busy && <LoadingTask />}{!!error && <Text accessibilityRole="alert" style={s.error}>{error}</Text>}
    {editing ? <ScrollView contentContainerStyle={{ gap: 16 }}>{confirmDelete ? <><Text style={s.body}>Delete “{label}” from the shared catalog, card tags, and saved search meanings?</Text><View style={s.row}><Action label="Cancel" disabled={busy} onPress={() => setConfirmDelete(false)} /><Action label="Delete tag" disabled={busy || conflict} onPress={() => run(async () => { const result = await api.request<{ tags: Tag[] }>('/admin/tags/' + encodeURIComponent(id), 'DELETE', { expected: original }); onTags(result.tags); setEditing(false); })} /></View></> : <><TextInput accessibilityLabel="Tag label" placeholder="Label" placeholderTextColor={c.muted} value={label} maxLength={60} onChangeText={value => { setLabel(value); if (!original) setId(value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60)); }} style={s.input} />{!original && <TextInput accessibilityLabel="Tag ID" placeholder="Tag ID" placeholderTextColor={c.muted} autoCapitalize="none" value={id} maxLength={60} onChangeText={setId} style={s.input} />}<SelectField label="Category" value={category} options={['color', 'environment', 'vibe', 'style', 'direction', 'subject'].map(value => ({ value, label: value[0].toUpperCase() + value.slice(1) }))} onChange={setCategory} /><TextInput accessibilityLabel="Aliases, separated by commas" placeholder="Aliases, separated by commas" placeholderTextColor={c.muted} multiline value={aliases} onChangeText={setAliases} style={[s.input, { minHeight: 90 }]} /><View style={s.row}><Action label="Save tag" primary disabled={busy || conflict || !label.trim() || !id} onPress={save} />{original && <Action label="Delete" disabled={busy || conflict} onPress={() => setConfirmDelete(true)} />}</View></>}{conflict && <Action label="Reload tags" disabled={busy} onPress={() => run(async () => { const refreshed = await api.bootstrap(); onTags(refreshed.tags); const latest = refreshed.tags.find(tag => tag.id === id); if (latest) begin(latest); else setEditing(false); })} />}</ScrollView> : <><View style={s.row}><TextInput accessibilityLabel="Find shared tags" placeholder="Find tags" placeholderTextColor={c.muted} value={query} onChangeText={setQuery} style={[s.input, { flex: 1 }]} /><Action label="+ New" onPress={() => begin(null)} /></View><FlatList data={tags.filter(tag => [tag.label, ...tag.aliases].some(value => value.toLowerCase().includes(query.toLowerCase())))} keyExtractor={tag => tag.id} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => begin(item)} style={s.item}><Text style={s.heading}>{item.label}</Text><Text style={s.caption}>{item.category}{item.aliases.length ? ' · ' + item.aliases.join(', ') : ''}</Text></Pressable>} /></>}
  </View>;
}
const s = StyleSheet.create({ root: { flex: 1, padding: 20, gap: 16, backgroundColor: c.background }, row: { flexDirection: 'row', gap: 8, alignItems: 'center' }, title: { ...t.title, color: c.text }, heading: { ...t.heading, color: c.text }, body: { ...t.body, color: c.secondary }, caption: { ...t.caption, color: c.secondary }, error: { ...t.body, color: c.danger }, input: { ...t.body, minHeight: 44, color: c.text, borderWidth: 1, borderColor: c.border, borderRadius: 6, padding: 12 }, item: { gap: 6, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: c.line } });
