import Modal from './DesktopDialog';
import React, { useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import Action from './Action';
import { colors as c, type as t } from '../design/tokens';
export default function SelectField({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState('');
  const shown = options.find(option => option.value === value)?.label ?? value;
  return <><Pressable accessibilityRole="button" accessibilityLabel={`${label}: ${shown || 'Any'}`} onPress={() => { setQuery(''); setOpen(true); }} style={s.button}><Text style={s.label}>{label} · {shown || 'Any'} ▾</Text></Pressable><Modal visible={open} presentationStyle="pageSheet" animationType="slide" onRequestClose={() => setOpen(false)}><View style={s.modal}><View style={{ flexDirection: 'row', alignItems: 'center' }}><Text style={[s.heading, { flex: 1 }]}>{label}</Text><Action label="Done" onPress={() => setOpen(false)} /></View>{options.length > 8 && <TextInput accessibilityLabel={`Find ${label.toLowerCase()}`} placeholder="Find…" placeholderTextColor={c.muted} value={query} onChangeText={setQuery} style={s.input} />}<FlatList data={options.filter(option => option.label.toLowerCase().includes(query.toLowerCase()))} keyExtractor={option => option.value} renderItem={({ item }) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: item.value === value }} onPress={() => { onChange(item.value); setOpen(false); }} style={[s.button, { marginBottom: 8 }]}><Text style={[s.label, item.value === value && { color: c.accent }]}>{item.label}</Text></Pressable>} /></View></Modal></>;
}
const s = StyleSheet.create({ button: { minHeight: 44, padding: 12, borderWidth: 1, borderColor: c.border, borderRadius: 6, justifyContent: 'center' }, label: { ...t.label, color: c.text }, heading: { ...t.heading, color: c.text }, input: { ...t.body, color: c.text, minHeight: 44, padding: 12, borderWidth: 1, borderColor: c.border, borderRadius: 6 }, modal: { flex: 1, padding: 20, gap: 16, backgroundColor: c.background } });
